### ISSUE TITLE
linux background colour is reset when reloading config

### ISSUE THREAD

**Issue by jvns** [ghostty-org/ghostty#3213] opened 2024-12-27 00:41 UTC
congrats on the 1.0 release! here's something small I ran into:

1. I set my background colour (and the rest of my colourscheme) using escape codes (using [this script](https://github.com/chriskempson/base16-shell/blob/master/scripts/base16-solarized-light.sh))
2. I reload ghostty's configuration with `Ctrl+Shift+,`
3. the background colour is reset to what I guess is the default background colour. The other colours in the colourscheme stay the same, it's just the background colour that changes

This is from

* ghostty at commit 35b9ceee2116331b83c0c86269394e2545070b0f, compiled from source
* with the default config
* It only happens on Linux, not on Mac OS

**Comment by gpanders** [comment] 2024-12-27 00:43
Duplicate of https://github.com/ghostty-org/ghostty/issues/2795

**Closed** 2024-12-27 00:57 UTC
