### ISSUE TITLE
Ghostty breaks when setting `gtk-titlebar = false`, and `gtk-tabs-location = hidden` on Linux

### ISSUE THREAD

**Issue by Ev357** [ghostty-org/ghostty#3178] opened 2024-12-26 23:11 UTC
Hi, i'm trying to configure tabs because i don't really want to use tmux, i just want to remove visualy the tabs completely, because they take space. My issue is when setting `gtk-tabs-location = hidden`. Ghostty breaks to one single color like this:

![Image](https://github.com/user-attachments/assets/1c828368-2274-42d8-a675-ca889842ba56)

I'm running Arch Linux with Hyprland, installed Ghostty by building it from source with zig.

**Comment by mitchellh** [comment] 2024-12-26 23:16
This has enough details that I want to see if this can be reproduced before moving to discussions.

**Comment by tomektom** [comment] 2024-12-27 00:52
I have same issue. Manjaro, also Hyprland, Ghostty build from AUR. Blank noninteractive block after adding `gtk-tabs-location = hidden`. My full config:
```
theme = GruvboxDark
window-theme = ghostty
font-size = 10
font-family = FiraMono Nerd Font
gtk-titlebar = false
gtk-tabs-location = hidden
```

**Comment by hozzaq** [comment] 2024-12-27 01:42
![Image](https://github.com/user-attachments/assets/18304cb5-8574-4307-be18-d352b8bab391)

same issue here Arch Linux with Hyprland

**Comment by roycrippen4** [comment] 2024-12-27 02:21
![Image](https://github.com/user-attachments/assets/19e85a4d-b306-4b34-9a48-46d92ca2e702)

Ghostty built from source via `zig build -p $HOME/.local -Doptimize=ReleaseFast`
I'm also running Arch Linux with Hyprland.

**Comment by taciturnaxolotl** [comment] 2024-12-27 03:22
Can confirm this happens to me too; built from the nix flake 15 minutes ago; also using hyprland.

![Image](https://github.com/user-attachments/assets/ca87a30d-a3c3-492c-b35c-4513ea285573)

**Comment by omagdy7** [comment] 2024-12-27 05:11
I don't think this is Hyprland specific it happens on awesomewm aswell and I installed the package via pacman

![Image](https://github.com/user-attachments/assets/64f62336-aae0-481a-a8dd-9bd5146a9c96)

**Comment by CraziestOwl** [comment] 2024-12-27 16:55
I have the same issue on kubuntu, i3. I have complied form source with tag v.1.0.0

**Comment by brtmax** [comment] 2024-12-27 21:53
Same issue on arch and wayland, but like mentioned above it also only happens when I set both 
`gtk-titlebar = false
gtk-tabs-location = hidden`
No issues when setting either of these alone

**Comment by fitrh** [comment] 2024-12-28 03:44
I can't reproduce the issue with 1.0.1-main+35b9ceee, GTK 4.16.7, Wayland

Has anyone experiencing this issue been able to reproduce it in HEAD? Also try running ghostty from the command line to see the logs

![Image](https://github.com/user-attachments/assets/e93fc7af-5f01-4053-8a32-98352c5ac60f)

**Comment by CraziestOwl** [comment] 2024-12-28 05:56
The logs look simular to when it work at the start, but it gets stuck after the line below.
If I try to open inspector ghostty crashes 

```
info: ghostty version=1.0.1-main+6cbd69da
info: ghostty build optimize=ReleaseFast
...
Enabled features (use GDK_GL_DISABLE env var to disable):
    debug: YES
    unpack-subimage: YES
    half-float: YES
    sync: YES
    base-instance: YES
    buffer-storage: YES
OpenGL version: 4.6 (core)
* GLSL version: 4.60 NVIDIA
* Max texture size: 32768

Enabled features (use GDK_GL_DISABLE env var to disable):
    debug: YES
    unpack-subimage: YES
    half-float: YES
    sync: YES
    base-instance: YES
    buffer-storage: YES

```

**Comment by OmriPH** [comment] 2024-12-28 15:20
![Image](https://github.com/user-attachments/assets/290c7718-6cbd-444a-b99d-837a73c0e5f2)
Happens to me on KDE Plasma, Arch Linux.

**Comment by shortfusemini** [comment] 2024-12-29 13:49
![Image](https://github.com/user-attachments/assets/0f0d6d46-c361-407f-8b23-078251006689)

Try setting `window-decoration` to `false`.

Refer to https://ghostty.org/docs/config/reference#gtk-titlebar

Works on Fedora 41 and swaywm.

**Comment by goproslowyo** [comment] 2024-12-29 14:18
In my case it causes a total crash of Ghostty with:

```
gtk-titlebar = false
gtk-tabs-location = hidden
```

I submitted the crashes to Sentry via sentry-cli:

```
body: {"id":"964831154c0b4f17b658fdaba032f1ab"}
body: {"id":"1c06f7dbea404811bbf6a9ed403e44d4"}
body: {"id":"c0a2911c227747fa49eb0ae333ff575f"}
body: {"id":"21099ab09fc4425c34f3ff90a8b28296"}
body: {"id":"8c02b0427e014356a9f6f8b0b76a22b5"}
body: {"id":"c891685ce6b049223158087a85b91915"}
```

**Comment by aman-4321** [comment] 2024-12-29 19:43
Same issue on arch and wayland, but like mentioned above it also only happens when I set both

    gtk-titlebar = false
    gtk-tabs-location = hidden

No issues when setting either of these alone

**Comment by tristan957** [comment] 2024-12-29 20:34
I'm trying to investigate 😄

**Comment by gmdias727** [comment] 2024-12-30 03:58
setting `window-decoration = false` disables GTK top bar meanwhile changing again to `window-decoration = true` the GTK breaks and doesn't restore the decoration.

![Image](https://github.com/user-attachments/assets/0f48f8fa-5e5e-4275-b163-4c3f303ee065)

**Comment by tristan957** [comment] 2024-12-30 04:28
If you're on GNOME, then I don't think not having window decorations works. There are no SSDs for Wayland applications on GNOME.

**Closed** 2024-12-30 16:55 UTC
Labels: os/linux, gui

**Comment by Ev357** [comment] 2024-12-30 17:48
thx u so much @mitchellh

**Comment by gmdias727** [comment] 2024-12-31 11:42
> If you're on GNOME, then I don't think not having window decorations works. There are no SSDs for Wayland applications on GNOME. I also don't understand what "breaks" means.

Sorry for the mis explanation, GTK doesn't breaks it just doesn't restore the top bar when you set to true but, substituting:

window-decoration = true

for

gtk-titlebar = true
gtk-tabs-location = top

works perfectly
