### ISSUE TITLE
build: support building with GTK compiled without x11-backend

### ISSUE THREAD

**Issue by ldv** [ghostty-org/ghostty#3477] opened 2024-12-27 16:46 UTC
**Build environment**: Fedora 41, _gtk4_ package compiled with _x11-backend_ option disabled.

I tried to build the package with:
_zig build -fsys=simdutf -Dtarget=native  -Doptimize=ReleaseFast -Dpie_

but it fails with the following errors:

```
install
└─ install ghostty
   └─ zig build-exe ghostty ReleaseFast native 2 errors
src/apprt/gtk/c.zig:2:15: error: C import failed
pub const c = @cImport({
              ^~~~~~~~
referenced by:
    gtk: src/cli/version.zig:8:80
    run: src/cli/version.zig:42:13
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
/home/ldv/Downloads/ghostty-1.0.0/.zig-cache/o/cfe3a1b5077a346ccf90ce9c54a404e4/cimport.h:3:10: error: 'gdk/x11/gdkx.h' file not found
#include <gdk/x11/gdkx.h>
```

Is there a plan to support "pure" Wayland GTK backend? Or am I missing something?

**Comment by mitchellh** [comment] 2024-12-27 16:47
This file is required for compilation but we don't use it at runtime if Wayland is used. We could introduce a build option to not complete the X11 support at all but I'm not sure if it's worth it... still I've tagged this to look into it.

**Comment by sin-ack** [comment] 2024-12-27 17:11
We also hit this issue in Gentoo packaging, as GTK 4 can be built without X. https://bugs.gentoo.org/947032

**Comment by mitchellh** [comment] 2024-12-27 17:38
Thanks for the additional data point. I'd like to fix this.

**Comment by tristan957** [comment] 2024-12-27 20:21
I tried fixing this one time, but I don't understand Zig's C support enough to fix it. If this was a C project, I would have it done, but I'm still new to Zig. Very interested to see what solutions can be come up with!

**Comment by mitchellh** [comment] 2024-12-27 20:23
> I tried fixing this one time, but I don't understand Zig's C support enough to fix it.

We need to introduce a build option that we then use to avoid ever referencing the `cImport` decl. Since Zig tree shakes, this will avoid trying to load and compile it.

**Comment by mitchellh** [comment] 2024-12-28 22:45
This should be fixed on main with #3748. I'd appreciate any confirmation, it should happen automatically now.

**Closed by mitchellh** 2024-12-28 22:45 UTC
Labels: packaging

**Comment by ldv** [comment] 2024-12-29 10:44
I tried to build from [master (c8950d3):](https://github.com/ghostty-org/ghostty/commit/c8950d376ab3be13fbd9a19317163075f4feddbc):

_zig build -fsys=simdutf -Dtarget=native -Doptimize=ReleaseFast -Dpie -Dgtk-x11=false -Dgtk-adwaita=false_

and it works, thank you!

**Comment by sin-ack** [comment] 2024-12-29 11:14
Also confirmed on a pure-Wayland Gentoo chroot.
